
package(default_visibility = ["//visibility:public"])
load("//defs:proto.bzl", "proto", "module")


# Regulatory
module(
    name = "opencannabis.regulatory",
    deps = ["//sources/public/models/regulatory/usa:opencannabis.regulatory.usa"],
    strip_import_prefix = "/sources/public/models")
