
package(default_visibility = ["//visibility:public"])
load("//tools/defs:proto.bzl", "proto", "module")


# Regulatory
module(
    name = "regulatory",
    deps = ["//opencannabis/regulatory/usa:opencannabis.regulatory.usa"],
    strip_import_prefix = "/sources/public/models")
