
package(default_visibility = ["//visibility:public"])
load("//defs:proto.bzl", "proto", "module")


# U.S. Regulatory
module(
    name = "opencannabis.regulatory.usa",
    deps = [
        "//opencannabis/regulatory/usa/ca:opencannabis.regulatory.usa.ca"],
    strip_import_prefix = "/sources/public/models")
